### ISSUE TITLE
Build failures between 1.1 and 1.2 (works on 1.0 though)

### ISSUE THREAD

**Issue by craigbarrau** [guregu/dynamo#92]
Really cool project! I found this through a library that depended upon it.

As a lazy developer, I often just do a "go get" to bring the dependency in. However, in my current setup I get build failures when I do this. I resolved that via instead cloning manually and then choosing "v1.0.0" tag. Anyway just wanted to let you know in case others are experiencing this too. Let me know if anything I can do to help. I put my logs below for what it is worth....

Running any of the following...

`git checkout tags/v1.1.0 && go build`
`git checkout tags/v1.1.1 && go build` 
`git checkout tags/v1.2.0 && go build`

...results in

```
./conditioncheck.go:65:46: undefined: dynamodb.TransactWriteItem
./delete.go:135:34: undefined: dynamodb.TransactWriteItem
./put.go:118:31: undefined: dynamodb.TransactWriteItem
./query.go:527:31: undefined: dynamodb.TransactGetItem
./tx.go:10:16: undefined: dynamodb.TransactGetItem
./tx.go:87:34: undefined: dynamodb.TransactGetItemsOutput
./tx.go:145:28: undefined: dynamodb.TransactGetItemsInput
./tx.go:161:18: undefined: dynamodb.TransactWriteItem
./tx.go:260:30: undefined: dynamodb.TransactWriteItemsInput
./tx.go:284:32: undefined: dynamodb.ItemResponse
./tx.go:284:32: too many errors
```

My workaround was to run `git checkout tags/v1.0.0 && go build`. When I did that it was able to build and it worked with the library that depends upon it. Hope this helps in some way.

**Comment by guregu** [comment]
Hello, thanks! 

I think the problem here is that your aws-sdk-go package is outdated. I added transactions in v1.1.0 which is a pretty new API (only a few months old) so it requires the newer AWS SDK. 

Have you tried running `go get -u` with the latest version of this lib? It should update your AWS stuff and fix the build.

It could also be a problem with the way Go modules work. It picks the lowest version between dependencies, so if something else if your build depends on an old version of the AWS SDK it might screw up the build. I'm still pretty new to modules so I'm not really sure how it works 100%.

**Comment by craigbarrau** [comment]
Thanks. Yes, that was it. Just needed to do the `go get -u github.com/aws/aws-sdk-go`. I'll close this.

**Comment by craigbarrau** [comment]
And to be clear it probably wasn't a `go.mod` issue.
I was building with pure GOPATH on 1.11
